namespace b1_chat_console.Models;

/// <summary>
/// Immutable identity of the catalog a V2 Scene was authored against. The hash is
/// generated by the catalog build pipeline; Scene files never carry wire IDs.
/// </summary>
public sealed record GestureCatalogIdentity(string Id, string Revision, string Hash);

public enum GestureExecutionKind { Immediate, Finite, Continuous }

public sealed record GestureTempoDefinition(string Key, int DurationMs);
public sealed record GestureTrajectoryFrameV2(int Pan, int Tilt, int MoveMs, int HoldMs, string Easing);
public sealed record GestureTrajectoryV2(IReadOnlyList<GestureTrajectoryFrameV2> Frames);
public sealed record GestureCompositionV2(string Layer, IReadOnlySet<string> Axes);

public sealed record GestureDefinitionV2(
    string Key,
    string DisplayName,
    string Description,
    string Family,
    IReadOnlyList<string> Tags,
    GestureExecutionKind Execution,
    string EndBehavior,
    GestureCompositionV2 Composition,
    IReadOnlyDictionary<string, GestureTempoDefinition> Tempos,
    IReadOnlySet<string> Intensities,
    IReadOnlySet<string> Variants,
    bool RequiresSeed,
    int MinimumMotionEngine,
    bool AuditionSafe,
    bool BroadcastSafe,
    GestureTrajectoryV2 Trajectory);

public sealed record GestureCatalogV2(
    GestureCatalogIdentity Identity,
    IReadOnlyDictionary<string, GestureDefinitionV2> Gestures);

public sealed record SceneTargetV2(bool IsBroadcast, ushort? DroidId)
{
    public static SceneTargetV2 Broadcast { get; } = new(true, null);
}

public sealed record SceneTrackV2(ushort DroidId, string Name);

public sealed record GestureClipV2(
    Guid Id,
    string GestureKey,
    SceneTargetV2 Target,
    int StartMs,
    string Intensity,
    string Tempo,
    string Variant,
    uint Seed,
    int? HoldMs);

public sealed record SceneAudioClipV2(string FilePath, int DurationMs, int StartMs, bool Loop);
public sealed record SceneAudioLaneV2(string Label, IReadOnlyList<SceneAudioClipV2> Clips);

public sealed record SceneV2(
    string Name,
    bool Loop,
    int? EndMs,
    GestureCatalogIdentity Catalog,
    IReadOnlyList<SceneTrackV2> Tracks,
    IReadOnlyList<SceneAudioLaneV2> AudioLanes,
    IReadOnlyList<GestureClipV2> GestureClips);
