using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using b1_chat_console.Models;
using b1_chat_console.ViewModels;

namespace b1_chat_console.Views;

// First mouse-capture/drag interaction in this app (see the Sequencer timeline plan) — kept
// intentionally simple/explicit: raw MouseLeftButtonDown/Move/Up + CaptureMouse, no Thumb, no
// native DragDrop (including the gesture-library "drag-and-drop", which is really the same
// mouse-capture idiom driving a floating ghost element rather than DragDrop.DoDragDrop).
public partial class SequenceTimelineView : UserControl
{
    private bool _draggingClip;
    private SequenceStep? _dragStep;
    private double _dragStartMouseX;
    private int _dragStartMs;

    private bool _draggingAudioClip;
    private AudioClip? _dragAudioClip;
    private double _dragAudioStartMouseX;
    private int _dragAudioStartMs;

    private bool _scrubbing;

    // Gesture-library click-vs-drag: MouseLeftButtonDown always captures and arms candidate
    // state; only once the mouse has moved past a small threshold does this become a real drag
    // (ghost shown, insertion deferred to MouseUp) — otherwise MouseUp falls back to today's
    // plain-click behavior (insert on the armed track at the playhead).
    private const double DragThresholdPx = 5;
    private bool _chipCandidate;
    private bool _chipDragging;
    private int _chipAnimId;
    private Point _chipDownPos;

    public SequenceTimelineView()
    {
        InitializeComponent();
    }

    private SequencerViewModel? Vm => DataContext as SequencerViewModel;

    // --- Gesture clip drag: StartMs (horizontal) + Target (vertical, retarget to another
    // droid's row). Clips aren't resizable — no user-editable duration exists in the protocol. ---

    private void Clip_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
    {
        if (sender is not FrameworkElement fe || fe.DataContext is not SequenceStep step || Vm is not { } vm) return;
        vm.SelectedStep = step;
        _dragStep = step;
        _dragStartMouseX = e.GetPosition(TracksCanvas).X;
        _dragStartMs = step.StartMs;
        _draggingClip = true;
        fe.CaptureMouse();
        vm.BeginStepDrag(); // once per gesture, not per pixel — Undo restores in one step
        e.Handled = true;
    }

    private void Clip_MouseMove(object sender, MouseEventArgs e)
    {
        if (!_draggingClip || _dragStep == null || Vm is not { } vm || vm.PxPerMs <= 0) return;
        var pos = e.GetPosition(TracksCanvas);
        var deltaMs = (pos.X - _dragStartMouseX) / vm.PxPerMs;
        var snapped = vm.RoundToGrid(_dragStartMs + deltaMs);
        _dragStep.StartMs = Math.Max(0, snapped);

        var track = vm.TrackAtY(pos.Y);
        if (track != null) _dragStep.Target = track.Id;
    }

    private void Clip_MouseLeftButtonUp(object sender, MouseButtonEventArgs e)
    {
        if (!_draggingClip) return;
        _draggingClip = false;
        _dragStep = null;
        if (sender is FrameworkElement fe) fe.ReleaseMouseCapture();
        // Settle the ruler/extent once at drag-end, not on every MouseMove (would jitter
        // under the cursor mid-drag).
        Vm?.RefreshTimelineExtent();
    }

    // --- Audio clip drag: StartMs only (horizontal within its own lane — clips don't move
    // between lanes, and overlap within a lane is allowed by design, not prevented here). ---

    // No single fixed Canvas exists for audio clips (each lane gets its own, generated by the
    // outer ItemsControl) — RootGrid is used purely as a stable measurement frame for the mouse
    // delta, same trick as the gesture-chip ghost drag below. Only the delta matters (current
    // minus start), so horizontal ScrollViewer scroll doesn't skew it: a pixel of mouse movement
    // is a pixel of delta in any non-scaling ancestor's coordinate space.
    private void AudioClip_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
    {
        if (sender is not FrameworkElement fe || fe.DataContext is not AudioClip clip || Vm is not { } vm) return;
        _dragAudioClip = clip;
        _dragAudioStartMouseX = e.GetPosition(RootGrid).X;
        _dragAudioStartMs = clip.StartMs;
        _draggingAudioClip = true;
        fe.CaptureMouse();
        vm.BeginAudioClipDrag();
        e.Handled = true;
    }

    private void AudioClip_MouseMove(object sender, MouseEventArgs e)
    {
        if (!_draggingAudioClip || _dragAudioClip == null || Vm is not { } vm || vm.PxPerMs <= 0) return;
        var x = e.GetPosition(RootGrid).X;
        var deltaMs = (x - _dragAudioStartMouseX) / vm.PxPerMs;
        var snapped = vm.RoundToGrid(_dragAudioStartMs + deltaMs);
        _dragAudioClip.StartMs = Math.Max(0, snapped);
    }

    private void AudioClip_MouseLeftButtonUp(object sender, MouseButtonEventArgs e)
    {
        if (!_draggingAudioClip) return;
        _draggingAudioClip = false;
        _dragAudioClip = null;
        if (sender is FrameworkElement fe) fe.ReleaseMouseCapture();
        Vm?.RefreshTimelineExtent();
    }

    // --- Ruler: local scrub (ignored while a real hardware playback is driving the
    // playhead — see SequencerViewModel.SetPlayheadFromPixel). ---

    private void Ruler_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
    {
        if (Vm == null) return;
        _scrubbing = true;
        ((UIElement)sender).CaptureMouse();
        Vm.SetPlayheadFromPixel(e.GetPosition(RulerCanvas).X);
    }

    private void Ruler_MouseMove(object sender, MouseEventArgs e)
    {
        if (!_scrubbing || Vm == null) return;
        Vm.SetPlayheadFromPixel(e.GetPosition(RulerCanvas).X);
    }

    private void Ruler_MouseLeftButtonUp(object sender, MouseButtonEventArgs e)
    {
        _scrubbing = false;
        ((UIElement)sender).ReleaseMouseCapture();
    }

    // --- Gesture library: plain click inserts on the armed track at the playhead (unchanged);
    // dragging past a small threshold instead drops the gesture on a specific droid+time cell. ---

    private void GestureChip_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
    {
        if (sender is not FrameworkElement fe || fe.DataContext is not GestureLibraryEntry entry) return;
        _chipCandidate = true;
        _chipDragging = false;
        _chipAnimId = entry.Id;
        _chipDownPos = e.GetPosition(RootGrid);
        fe.CaptureMouse();
        e.Handled = true;
    }

    private void GestureChip_MouseMove(object sender, MouseEventArgs e)
    {
        if (!_chipCandidate) return;
        var pos = e.GetPosition(RootGrid);

        if (!_chipDragging)
        {
            var moved = Math.Abs(pos.X - _chipDownPos.X) + Math.Abs(pos.Y - _chipDownPos.Y);
            if (moved < DragThresholdPx) return;
            _chipDragging = true;
            GhostText.Text = Vm?.GestureLibrary.FirstOrDefault(g => g.Id == _chipAnimId)?.Name ?? "";
            GhostBorder.Background = sender is FrameworkElement fe ? fe.GetValue(Border.BackgroundProperty) as System.Windows.Media.Brush : null;
            GhostBorder.Visibility = Visibility.Visible;
        }

        Canvas.SetLeft(GhostBorder, pos.X + 10);
        Canvas.SetTop(GhostBorder, pos.Y + 10);
    }

    private void GestureChip_MouseLeftButtonUp(object sender, MouseButtonEventArgs e)
    {
        if (!_chipCandidate) return;
        _chipCandidate = false;
        if (sender is FrameworkElement fe) fe.ReleaseMouseCapture();

        if (!_chipDragging)
        {
            // Plain click — today's behavior, insert on the armed track at the playhead.
            Vm?.InsertGestureCommand.Execute(_chipAnimId);
            return;
        }

        _chipDragging = false;
        GhostBorder.Visibility = Visibility.Collapsed;

        if (Vm is not { } vm) return;
        var posInTracks = e.GetPosition(TracksCanvas);
        var withinX = posInTracks.X >= 0 && posInTracks.X <= TracksCanvas.ActualWidth;
        var withinY = posInTracks.Y >= 0 && posInTracks.Y <= TracksCanvas.ActualHeight;
        if (!withinX || !withinY) return; // dropped outside the timeline: cancel, nothing inserted

        var startMs = vm.RoundToGrid(posInTracks.X / vm.PxPerMs);
        var track = vm.TrackAtY(posInTracks.Y);
        vm.InsertGestureAt(_chipAnimId, track, startMs);
    }
}
