param(
    [switch]$Verify,
    [switch]$UpdateHash
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$catalogPath = Join-Path $root 'catalog\gesture-catalog-v1.json'
$outputPath = Join-Path $root 'src\generated\gesture_catalog_v2.h'
$catalogJson = Get-Content -Raw $catalogPath

function Get-CatalogHash([string]$json) {
    # The declared hash is replaced with zeroes before hashing. This avoids a
    # self-referential digest while making every other catalog byte significant.
    $normalized = $json.Replace("`r`n", "`n").Replace("`r", "`n")
    $masked = [regex]::Replace($normalized,
        '("hash"\s*:\s*"sha256:)[0-9a-f]{64}', '${1}' + ('0' * 64))
    $sha = [Security.Cryptography.SHA256]::Create()
    try {
        $digest = $sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($masked))
        return 'sha256:' + ([BitConverter]::ToString($digest).Replace('-', '').ToLowerInvariant())
    } finally {
        $sha.Dispose()
    }
}

$computedHash = Get-CatalogHash $catalogJson
$declaredHash = ([regex]::Match($catalogJson, '"hash"\s*:\s*"(sha256:[0-9a-f]{64})"')).Groups[1].Value
if ($declaredHash -ne $computedHash) {
    if (-not $UpdateHash) {
        throw "Catalog hash is invalid. Expected $computedHash but found $declaredHash. Run .\tools\generate-gesture-catalog.ps1 -UpdateHash."
    }
    $catalogJson = [regex]::Replace($catalogJson,
        '("hash"\s*:\s*")sha256:[0-9a-f]{64}"',
        { param($match) $match.Groups[1].Value + $computedHash + '"' }, 1)
    Set-Content -LiteralPath $catalogPath -Value $catalogJson -NoNewline -Encoding utf8
}
$catalog = $catalogJson | ConvertFrom-Json

function WireName([string]$key) {
    return 'GESTURE_' + (($key -replace '[^A-Za-z0-9]', '_').ToUpperInvariant())
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// <auto-generated />')
$lines.Add('// Generated from catalog/gesture-catalog-v1.json. Do not edit by hand.')
$lines.Add('#pragma once')
$lines.Add('#include <Arduino.h>')
$lines.Add('')
$lines.Add(('static const char* const GESTURE_CATALOG_ID = "{0}";' -f $catalog.catalogId))
$lines.Add(('static const char* const GESTURE_CATALOG_REVISION = "{0}";' -f $catalog.revision))
$lines.Add(('static const char* const GESTURE_CATALOG_HASH = "{0}";' -f $catalog.hash))
$lines.Add('enum GestureWireId : uint8_t {')
for ($i = 0; $i -lt $catalog.gestures.Count; $i++) {
    $lines.Add(('    {0} = {1},' -f (WireName $catalog.gestures[$i].key), $i))
}
$lines.Add(('    GESTURE_COUNT = {0}' -f $catalog.gestures.Count))
$lines.Add('};')
$lines.Add('enum GestureExecutionKindV2 : uint8_t { GESTURE_IMMEDIATE, GESTURE_FINITE, GESTURE_CONTINUOUS };')
$lines.Add('enum GestureCompositionLayerV2 : uint8_t { GESTURE_LAYER_RESET, GESTURE_LAYER_BASE, GESTURE_LAYER_OVERLAY };')
$lines.Add('enum GestureAxisMaskV2 : uint8_t { GESTURE_AXIS_NONE = 0, GESTURE_AXIS_PAN = 1, GESTURE_AXIS_TILT = 2, GESTURE_AXIS_BOTH = 3 };')
$lines.Add('enum GestureEndBehaviorV2 : uint8_t { GESTURE_END_RESET_ALL, GESTURE_END_HOLD_POSE, GESTURE_END_CLEAR_LAYER };')
$lines.Add('struct GestureFrameV2 { int8_t panPct; int8_t tiltPct; uint16_t moveMs; uint16_t holdMs; };')
$lines.Add('struct GestureDefinitionV2 { const char* key; GestureExecutionKindV2 execution; GestureCompositionLayerV2 layer; uint8_t axes; GestureEndBehaviorV2 endBehavior; const GestureFrameV2* frames; uint8_t frameCount; uint16_t normalDurationMs; };')
$lines.Add('')
foreach ($gesture in $catalog.gestures) {
    $name = (WireName $gesture.key) -replace '^GESTURE_', ''
    if ($gesture.trajectory.frames.Count -gt 0) {
        $lines.Add(('static const GestureFrameV2 {0}_FRAMES[] = {{' -f $name))
        foreach ($frame in $gesture.trajectory.frames) {
            $lines.Add(('    {{ {0}, {1}, {2}, {3} }},' -f $frame.pan, $frame.tilt, $frame.moveMs, $frame.holdMs))
        }
        $lines.Add('};')
    }
}
$lines.Add('static const GestureDefinitionV2 GESTURES_V2[GESTURE_COUNT] = {')
foreach ($gesture in $catalog.gestures) {
    $name = (WireName $gesture.key) -replace '^GESTURE_', ''
    $execution = switch ($gesture.execution) { 'immediate' { 'GESTURE_IMMEDIATE' } 'finite' { 'GESTURE_FINITE' } default { 'GESTURE_CONTINUOUS' } }
    $frames = if ($gesture.trajectory.frames.Count -gt 0) { $name + '_FRAMES' } else { 'nullptr' }
    $count = $gesture.trajectory.frames.Count
    $duration = ($gesture.tempos | Where-Object key -eq 'normal').durationMs
    $layer = switch ($gesture.composition.layer) { 'reset' { 'GESTURE_LAYER_RESET' } 'base' { 'GESTURE_LAYER_BASE' } 'overlay' { 'GESTURE_LAYER_OVERLAY' } default { throw "Unsupported composition layer $($gesture.composition.layer)" } }
    $axes = 0
    foreach ($axis in $gesture.composition.axes) {
        switch ($axis) { 'pan' { $axes = $axes -bor 1 } 'tilt' { $axes = $axes -bor 2 } default { throw "Unsupported composition axis $axis" } }
    }
    $axisName = switch ($axes) { 1 { 'GESTURE_AXIS_PAN' } 2 { 'GESTURE_AXIS_TILT' } 3 { 'GESTURE_AXIS_BOTH' } default { throw "Gesture $($gesture.key) has no composition axis" } }
    $endBehavior = switch ($gesture.endBehavior) { 'resetAll' { 'GESTURE_END_RESET_ALL' } 'holdPose' { 'GESTURE_END_HOLD_POSE' } 'clearLayer' { 'GESTURE_END_CLEAR_LAYER' } default { throw "Unsupported end behavior $($gesture.endBehavior)" } }
    $lines.Add(('    {{ "{0}", {1}, {2}, {3}, {4}, {5}, {6}, {7} }},' -f $gesture.key, $execution, $layer, $axisName, $endBehavior, $frames, $count, $duration))
}
$lines.Add('};')
$contents = ($lines -join "`n") + "`n"

if ($Verify) {
    if (-not (Test-Path $outputPath) -or (Get-Content -Raw $outputPath) -ne $contents) {
        throw 'Generated gesture catalog is stale. Run .\tools\generate-gesture-catalog.ps1.'
    }
    exit 0
}

New-Item -ItemType Directory -Force (Split-Path -Parent $outputPath) | Out-Null
Set-Content -LiteralPath $outputPath -Value $contents -NoNewline -Encoding utf8
